### ISSUE TITLE
微信不可用

### ISSUE THREAD

**Issue by gudepeng** [PeterAlbus/vue3-social-share#1]
微信分享不可用，也不报错

**Comment by PeterAlbus** [comment]
close是解决了吗，微信这个是生成一个二维码，微信扫完打开这个网页分享，传入组件的网页url没有问题理论上就没有问题

**Comment by gudepeng** [comment]
嗯，解决完了。图层的问题。9有点小，并且那个样式只往上层显示弹窗，就被挡住了。
